// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/service-template/pkg/db/ent/general"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// GeneralCreate is the builder for creating a General entity.
type GeneralCreate struct {
	config
	mutation *GeneralMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (gc *GeneralCreate) SetCreatedAt(u uint32) *GeneralCreate {
	gc.mutation.SetCreatedAt(u)
	return gc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (gc *GeneralCreate) SetNillableCreatedAt(u *uint32) *GeneralCreate {
	if u != nil {
		gc.SetCreatedAt(*u)
	}
	return gc
}

// SetUpdatedAt sets the "updated_at" field.
func (gc *GeneralCreate) SetUpdatedAt(u uint32) *GeneralCreate {
	gc.mutation.SetUpdatedAt(u)
	return gc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (gc *GeneralCreate) SetNillableUpdatedAt(u *uint32) *GeneralCreate {
	if u != nil {
		gc.SetUpdatedAt(*u)
	}
	return gc
}

// SetDeletedAt sets the "deleted_at" field.
func (gc *GeneralCreate) SetDeletedAt(u uint32) *GeneralCreate {
	gc.mutation.SetDeletedAt(u)
	return gc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (gc *GeneralCreate) SetNillableDeletedAt(u *uint32) *GeneralCreate {
	if u != nil {
		gc.SetDeletedAt(*u)
	}
	return gc
}

// SetAppID sets the "app_id" field.
func (gc *GeneralCreate) SetAppID(u uuid.UUID) *GeneralCreate {
	gc.mutation.SetAppID(u)
	return gc
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (gc *GeneralCreate) SetNillableAppID(u *uuid.UUID) *GeneralCreate {
	if u != nil {
		gc.SetAppID(*u)
	}
	return gc
}

// SetUserID sets the "user_id" field.
func (gc *GeneralCreate) SetUserID(u uuid.UUID) *GeneralCreate {
	gc.mutation.SetUserID(u)
	return gc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (gc *GeneralCreate) SetNillableUserID(u *uuid.UUID) *GeneralCreate {
	if u != nil {
		gc.SetUserID(*u)
	}
	return gc
}

// SetCoinTypeID sets the "coin_type_id" field.
func (gc *GeneralCreate) SetCoinTypeID(u uuid.UUID) *GeneralCreate {
	gc.mutation.SetCoinTypeID(u)
	return gc
}

// SetNillableCoinTypeID sets the "coin_type_id" field if the given value is not nil.
func (gc *GeneralCreate) SetNillableCoinTypeID(u *uuid.UUID) *GeneralCreate {
	if u != nil {
		gc.SetCoinTypeID(*u)
	}
	return gc
}

// SetIncoming sets the "incoming" field.
func (gc *GeneralCreate) SetIncoming(d decimal.Decimal) *GeneralCreate {
	gc.mutation.SetIncoming(d)
	return gc
}

// SetNillableIncoming sets the "incoming" field if the given value is not nil.
func (gc *GeneralCreate) SetNillableIncoming(d *decimal.Decimal) *GeneralCreate {
	if d != nil {
		gc.SetIncoming(*d)
	}
	return gc
}

// SetLocked sets the "locked" field.
func (gc *GeneralCreate) SetLocked(d decimal.Decimal) *GeneralCreate {
	gc.mutation.SetLocked(d)
	return gc
}

// SetNillableLocked sets the "locked" field if the given value is not nil.
func (gc *GeneralCreate) SetNillableLocked(d *decimal.Decimal) *GeneralCreate {
	if d != nil {
		gc.SetLocked(*d)
	}
	return gc
}

// SetOutcoming sets the "outcoming" field.
func (gc *GeneralCreate) SetOutcoming(d decimal.Decimal) *GeneralCreate {
	gc.mutation.SetOutcoming(d)
	return gc
}

// SetNillableOutcoming sets the "outcoming" field if the given value is not nil.
func (gc *GeneralCreate) SetNillableOutcoming(d *decimal.Decimal) *GeneralCreate {
	if d != nil {
		gc.SetOutcoming(*d)
	}
	return gc
}

// SetSpendable sets the "spendable" field.
func (gc *GeneralCreate) SetSpendable(d decimal.Decimal) *GeneralCreate {
	gc.mutation.SetSpendable(d)
	return gc
}

// SetNillableSpendable sets the "spendable" field if the given value is not nil.
func (gc *GeneralCreate) SetNillableSpendable(d *decimal.Decimal) *GeneralCreate {
	if d != nil {
		gc.SetSpendable(*d)
	}
	return gc
}

// SetID sets the "id" field.
func (gc *GeneralCreate) SetID(u uuid.UUID) *GeneralCreate {
	gc.mutation.SetID(u)
	return gc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (gc *GeneralCreate) SetNillableID(u *uuid.UUID) *GeneralCreate {
	if u != nil {
		gc.SetID(*u)
	}
	return gc
}

// Mutation returns the GeneralMutation object of the builder.
func (gc *GeneralCreate) Mutation() *GeneralMutation {
	return gc.mutation
}

// Save creates the General in the database.
func (gc *GeneralCreate) Save(ctx context.Context) (*General, error) {
	var (
		err  error
		node *General
	)
	if err := gc.defaults(); err != nil {
		return nil, err
	}
	if len(gc.hooks) == 0 {
		if err = gc.check(); err != nil {
			return nil, err
		}
		node, err = gc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GeneralMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = gc.check(); err != nil {
				return nil, err
			}
			gc.mutation = mutation
			if node, err = gc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(gc.hooks) - 1; i >= 0; i-- {
			if gc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GeneralCreate) SaveX(ctx context.Context) *General {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gc *GeneralCreate) Exec(ctx context.Context) error {
	_, err := gc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gc *GeneralCreate) ExecX(ctx context.Context) {
	if err := gc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gc *GeneralCreate) defaults() error {
	if _, ok := gc.mutation.CreatedAt(); !ok {
		if general.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized general.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := general.DefaultCreatedAt()
		gc.mutation.SetCreatedAt(v)
	}
	if _, ok := gc.mutation.UpdatedAt(); !ok {
		if general.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized general.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := general.DefaultUpdatedAt()
		gc.mutation.SetUpdatedAt(v)
	}
	if _, ok := gc.mutation.DeletedAt(); !ok {
		if general.DefaultDeletedAt == nil {
			return fmt.Errorf("ent: uninitialized general.DefaultDeletedAt (forgotten import ent/runtime?)")
		}
		v := general.DefaultDeletedAt()
		gc.mutation.SetDeletedAt(v)
	}
	if _, ok := gc.mutation.AppID(); !ok {
		if general.DefaultAppID == nil {
			return fmt.Errorf("ent: uninitialized general.DefaultAppID (forgotten import ent/runtime?)")
		}
		v := general.DefaultAppID()
		gc.mutation.SetAppID(v)
	}
	if _, ok := gc.mutation.UserID(); !ok {
		if general.DefaultUserID == nil {
			return fmt.Errorf("ent: uninitialized general.DefaultUserID (forgotten import ent/runtime?)")
		}
		v := general.DefaultUserID()
		gc.mutation.SetUserID(v)
	}
	if _, ok := gc.mutation.CoinTypeID(); !ok {
		if general.DefaultCoinTypeID == nil {
			return fmt.Errorf("ent: uninitialized general.DefaultCoinTypeID (forgotten import ent/runtime?)")
		}
		v := general.DefaultCoinTypeID()
		gc.mutation.SetCoinTypeID(v)
	}
	if _, ok := gc.mutation.Incoming(); !ok {
		v := general.DefaultIncoming
		gc.mutation.SetIncoming(v)
	}
	if _, ok := gc.mutation.Locked(); !ok {
		v := general.DefaultLocked
		gc.mutation.SetLocked(v)
	}
	if _, ok := gc.mutation.Outcoming(); !ok {
		v := general.DefaultOutcoming
		gc.mutation.SetOutcoming(v)
	}
	if _, ok := gc.mutation.Spendable(); !ok {
		v := general.DefaultSpendable
		gc.mutation.SetSpendable(v)
	}
	if _, ok := gc.mutation.ID(); !ok {
		if general.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized general.DefaultID (forgotten import ent/runtime?)")
		}
		v := general.DefaultID()
		gc.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (gc *GeneralCreate) check() error {
	if _, ok := gc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "General.created_at"`)}
	}
	if _, ok := gc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "General.updated_at"`)}
	}
	if _, ok := gc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "General.deleted_at"`)}
	}
	return nil
}

func (gc *GeneralCreate) sqlSave(ctx context.Context) (*General, error) {
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (gc *GeneralCreate) createSpec() (*General, *sqlgraph.CreateSpec) {
	var (
		_node = &General{config: gc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: general.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: general.FieldID,
			},
		}
	)
	_spec.OnConflict = gc.conflict
	if id, ok := gc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := gc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: general.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := gc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: general.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := gc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: general.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if value, ok := gc.mutation.AppID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: general.FieldAppID,
		})
		_node.AppID = value
	}
	if value, ok := gc.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: general.FieldUserID,
		})
		_node.UserID = value
	}
	if value, ok := gc.mutation.CoinTypeID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: general.FieldCoinTypeID,
		})
		_node.CoinTypeID = value
	}
	if value, ok := gc.mutation.Incoming(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: general.FieldIncoming,
		})
		_node.Incoming = value
	}
	if value, ok := gc.mutation.Locked(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: general.FieldLocked,
		})
		_node.Locked = value
	}
	if value, ok := gc.mutation.Outcoming(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: general.FieldOutcoming,
		})
		_node.Outcoming = value
	}
	if value, ok := gc.mutation.Spendable(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: general.FieldSpendable,
		})
		_node.Spendable = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.General.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GeneralUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (gc *GeneralCreate) OnConflict(opts ...sql.ConflictOption) *GeneralUpsertOne {
	gc.conflict = opts
	return &GeneralUpsertOne{
		create: gc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.General.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (gc *GeneralCreate) OnConflictColumns(columns ...string) *GeneralUpsertOne {
	gc.conflict = append(gc.conflict, sql.ConflictColumns(columns...))
	return &GeneralUpsertOne{
		create: gc,
	}
}

type (
	// GeneralUpsertOne is the builder for "upsert"-ing
	//  one General node.
	GeneralUpsertOne struct {
		create *GeneralCreate
	}

	// GeneralUpsert is the "OnConflict" setter.
	GeneralUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *GeneralUpsert) SetCreatedAt(v uint32) *GeneralUpsert {
	u.Set(general.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GeneralUpsert) UpdateCreatedAt() *GeneralUpsert {
	u.SetExcluded(general.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *GeneralUpsert) AddCreatedAt(v uint32) *GeneralUpsert {
	u.Add(general.FieldCreatedAt, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GeneralUpsert) SetUpdatedAt(v uint32) *GeneralUpsert {
	u.Set(general.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GeneralUpsert) UpdateUpdatedAt() *GeneralUpsert {
	u.SetExcluded(general.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *GeneralUpsert) AddUpdatedAt(v uint32) *GeneralUpsert {
	u.Add(general.FieldUpdatedAt, v)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GeneralUpsert) SetDeletedAt(v uint32) *GeneralUpsert {
	u.Set(general.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GeneralUpsert) UpdateDeletedAt() *GeneralUpsert {
	u.SetExcluded(general.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *GeneralUpsert) AddDeletedAt(v uint32) *GeneralUpsert {
	u.Add(general.FieldDeletedAt, v)
	return u
}

// SetAppID sets the "app_id" field.
func (u *GeneralUpsert) SetAppID(v uuid.UUID) *GeneralUpsert {
	u.Set(general.FieldAppID, v)
	return u
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *GeneralUpsert) UpdateAppID() *GeneralUpsert {
	u.SetExcluded(general.FieldAppID)
	return u
}

// ClearAppID clears the value of the "app_id" field.
func (u *GeneralUpsert) ClearAppID() *GeneralUpsert {
	u.SetNull(general.FieldAppID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *GeneralUpsert) SetUserID(v uuid.UUID) *GeneralUpsert {
	u.Set(general.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GeneralUpsert) UpdateUserID() *GeneralUpsert {
	u.SetExcluded(general.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *GeneralUpsert) ClearUserID() *GeneralUpsert {
	u.SetNull(general.FieldUserID)
	return u
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *GeneralUpsert) SetCoinTypeID(v uuid.UUID) *GeneralUpsert {
	u.Set(general.FieldCoinTypeID, v)
	return u
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *GeneralUpsert) UpdateCoinTypeID() *GeneralUpsert {
	u.SetExcluded(general.FieldCoinTypeID)
	return u
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *GeneralUpsert) ClearCoinTypeID() *GeneralUpsert {
	u.SetNull(general.FieldCoinTypeID)
	return u
}

// SetIncoming sets the "incoming" field.
func (u *GeneralUpsert) SetIncoming(v decimal.Decimal) *GeneralUpsert {
	u.Set(general.FieldIncoming, v)
	return u
}

// UpdateIncoming sets the "incoming" field to the value that was provided on create.
func (u *GeneralUpsert) UpdateIncoming() *GeneralUpsert {
	u.SetExcluded(general.FieldIncoming)
	return u
}

// ClearIncoming clears the value of the "incoming" field.
func (u *GeneralUpsert) ClearIncoming() *GeneralUpsert {
	u.SetNull(general.FieldIncoming)
	return u
}

// SetLocked sets the "locked" field.
func (u *GeneralUpsert) SetLocked(v decimal.Decimal) *GeneralUpsert {
	u.Set(general.FieldLocked, v)
	return u
}

// UpdateLocked sets the "locked" field to the value that was provided on create.
func (u *GeneralUpsert) UpdateLocked() *GeneralUpsert {
	u.SetExcluded(general.FieldLocked)
	return u
}

// ClearLocked clears the value of the "locked" field.
func (u *GeneralUpsert) ClearLocked() *GeneralUpsert {
	u.SetNull(general.FieldLocked)
	return u
}

// SetOutcoming sets the "outcoming" field.
func (u *GeneralUpsert) SetOutcoming(v decimal.Decimal) *GeneralUpsert {
	u.Set(general.FieldOutcoming, v)
	return u
}

// UpdateOutcoming sets the "outcoming" field to the value that was provided on create.
func (u *GeneralUpsert) UpdateOutcoming() *GeneralUpsert {
	u.SetExcluded(general.FieldOutcoming)
	return u
}

// ClearOutcoming clears the value of the "outcoming" field.
func (u *GeneralUpsert) ClearOutcoming() *GeneralUpsert {
	u.SetNull(general.FieldOutcoming)
	return u
}

// SetSpendable sets the "spendable" field.
func (u *GeneralUpsert) SetSpendable(v decimal.Decimal) *GeneralUpsert {
	u.Set(general.FieldSpendable, v)
	return u
}

// UpdateSpendable sets the "spendable" field to the value that was provided on create.
func (u *GeneralUpsert) UpdateSpendable() *GeneralUpsert {
	u.SetExcluded(general.FieldSpendable)
	return u
}

// ClearSpendable clears the value of the "spendable" field.
func (u *GeneralUpsert) ClearSpendable() *GeneralUpsert {
	u.SetNull(general.FieldSpendable)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.General.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(general.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *GeneralUpsertOne) UpdateNewValues() *GeneralUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(general.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.General.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *GeneralUpsertOne) Ignore() *GeneralUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GeneralUpsertOne) DoNothing() *GeneralUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GeneralCreate.OnConflict
// documentation for more info.
func (u *GeneralUpsertOne) Update(set func(*GeneralUpsert)) *GeneralUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GeneralUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *GeneralUpsertOne) SetCreatedAt(v uint32) *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *GeneralUpsertOne) AddCreatedAt(v uint32) *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GeneralUpsertOne) UpdateCreatedAt() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GeneralUpsertOne) SetUpdatedAt(v uint32) *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *GeneralUpsertOne) AddUpdatedAt(v uint32) *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GeneralUpsertOne) UpdateUpdatedAt() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GeneralUpsertOne) SetDeletedAt(v uint32) *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *GeneralUpsertOne) AddDeletedAt(v uint32) *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GeneralUpsertOne) UpdateDeletedAt() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetAppID sets the "app_id" field.
func (u *GeneralUpsertOne) SetAppID(v uuid.UUID) *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *GeneralUpsertOne) UpdateAppID() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateAppID()
	})
}

// ClearAppID clears the value of the "app_id" field.
func (u *GeneralUpsertOne) ClearAppID() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearAppID()
	})
}

// SetUserID sets the "user_id" field.
func (u *GeneralUpsertOne) SetUserID(v uuid.UUID) *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GeneralUpsertOne) UpdateUserID() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *GeneralUpsertOne) ClearUserID() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearUserID()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *GeneralUpsertOne) SetCoinTypeID(v uuid.UUID) *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *GeneralUpsertOne) UpdateCoinTypeID() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateCoinTypeID()
	})
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *GeneralUpsertOne) ClearCoinTypeID() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearCoinTypeID()
	})
}

// SetIncoming sets the "incoming" field.
func (u *GeneralUpsertOne) SetIncoming(v decimal.Decimal) *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.SetIncoming(v)
	})
}

// UpdateIncoming sets the "incoming" field to the value that was provided on create.
func (u *GeneralUpsertOne) UpdateIncoming() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateIncoming()
	})
}

// ClearIncoming clears the value of the "incoming" field.
func (u *GeneralUpsertOne) ClearIncoming() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearIncoming()
	})
}

// SetLocked sets the "locked" field.
func (u *GeneralUpsertOne) SetLocked(v decimal.Decimal) *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.SetLocked(v)
	})
}

// UpdateLocked sets the "locked" field to the value that was provided on create.
func (u *GeneralUpsertOne) UpdateLocked() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateLocked()
	})
}

// ClearLocked clears the value of the "locked" field.
func (u *GeneralUpsertOne) ClearLocked() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearLocked()
	})
}

// SetOutcoming sets the "outcoming" field.
func (u *GeneralUpsertOne) SetOutcoming(v decimal.Decimal) *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.SetOutcoming(v)
	})
}

// UpdateOutcoming sets the "outcoming" field to the value that was provided on create.
func (u *GeneralUpsertOne) UpdateOutcoming() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateOutcoming()
	})
}

// ClearOutcoming clears the value of the "outcoming" field.
func (u *GeneralUpsertOne) ClearOutcoming() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearOutcoming()
	})
}

// SetSpendable sets the "spendable" field.
func (u *GeneralUpsertOne) SetSpendable(v decimal.Decimal) *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.SetSpendable(v)
	})
}

// UpdateSpendable sets the "spendable" field to the value that was provided on create.
func (u *GeneralUpsertOne) UpdateSpendable() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateSpendable()
	})
}

// ClearSpendable clears the value of the "spendable" field.
func (u *GeneralUpsertOne) ClearSpendable() *GeneralUpsertOne {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearSpendable()
	})
}

// Exec executes the query.
func (u *GeneralUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GeneralCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GeneralUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GeneralUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: GeneralUpsertOne.ID is not supported by MySQL driver. Use GeneralUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GeneralUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GeneralCreateBulk is the builder for creating many General entities in bulk.
type GeneralCreateBulk struct {
	config
	builders []*GeneralCreate
	conflict []sql.ConflictOption
}

// Save creates the General entities in the database.
func (gcb *GeneralCreateBulk) Save(ctx context.Context) ([]*General, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*General, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GeneralMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = gcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GeneralCreateBulk) SaveX(ctx context.Context) []*General {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcb *GeneralCreateBulk) Exec(ctx context.Context) error {
	_, err := gcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcb *GeneralCreateBulk) ExecX(ctx context.Context) {
	if err := gcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.General.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GeneralUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (gcb *GeneralCreateBulk) OnConflict(opts ...sql.ConflictOption) *GeneralUpsertBulk {
	gcb.conflict = opts
	return &GeneralUpsertBulk{
		create: gcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.General.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (gcb *GeneralCreateBulk) OnConflictColumns(columns ...string) *GeneralUpsertBulk {
	gcb.conflict = append(gcb.conflict, sql.ConflictColumns(columns...))
	return &GeneralUpsertBulk{
		create: gcb,
	}
}

// GeneralUpsertBulk is the builder for "upsert"-ing
// a bulk of General nodes.
type GeneralUpsertBulk struct {
	create *GeneralCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.General.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(general.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *GeneralUpsertBulk) UpdateNewValues() *GeneralUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(general.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.General.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *GeneralUpsertBulk) Ignore() *GeneralUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GeneralUpsertBulk) DoNothing() *GeneralUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GeneralCreateBulk.OnConflict
// documentation for more info.
func (u *GeneralUpsertBulk) Update(set func(*GeneralUpsert)) *GeneralUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GeneralUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *GeneralUpsertBulk) SetCreatedAt(v uint32) *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *GeneralUpsertBulk) AddCreatedAt(v uint32) *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *GeneralUpsertBulk) UpdateCreatedAt() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GeneralUpsertBulk) SetUpdatedAt(v uint32) *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *GeneralUpsertBulk) AddUpdatedAt(v uint32) *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GeneralUpsertBulk) UpdateUpdatedAt() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GeneralUpsertBulk) SetDeletedAt(v uint32) *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *GeneralUpsertBulk) AddDeletedAt(v uint32) *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GeneralUpsertBulk) UpdateDeletedAt() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetAppID sets the "app_id" field.
func (u *GeneralUpsertBulk) SetAppID(v uuid.UUID) *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.SetAppID(v)
	})
}

// UpdateAppID sets the "app_id" field to the value that was provided on create.
func (u *GeneralUpsertBulk) UpdateAppID() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateAppID()
	})
}

// ClearAppID clears the value of the "app_id" field.
func (u *GeneralUpsertBulk) ClearAppID() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearAppID()
	})
}

// SetUserID sets the "user_id" field.
func (u *GeneralUpsertBulk) SetUserID(v uuid.UUID) *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *GeneralUpsertBulk) UpdateUserID() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *GeneralUpsertBulk) ClearUserID() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearUserID()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *GeneralUpsertBulk) SetCoinTypeID(v uuid.UUID) *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *GeneralUpsertBulk) UpdateCoinTypeID() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateCoinTypeID()
	})
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *GeneralUpsertBulk) ClearCoinTypeID() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearCoinTypeID()
	})
}

// SetIncoming sets the "incoming" field.
func (u *GeneralUpsertBulk) SetIncoming(v decimal.Decimal) *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.SetIncoming(v)
	})
}

// UpdateIncoming sets the "incoming" field to the value that was provided on create.
func (u *GeneralUpsertBulk) UpdateIncoming() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateIncoming()
	})
}

// ClearIncoming clears the value of the "incoming" field.
func (u *GeneralUpsertBulk) ClearIncoming() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearIncoming()
	})
}

// SetLocked sets the "locked" field.
func (u *GeneralUpsertBulk) SetLocked(v decimal.Decimal) *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.SetLocked(v)
	})
}

// UpdateLocked sets the "locked" field to the value that was provided on create.
func (u *GeneralUpsertBulk) UpdateLocked() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateLocked()
	})
}

// ClearLocked clears the value of the "locked" field.
func (u *GeneralUpsertBulk) ClearLocked() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearLocked()
	})
}

// SetOutcoming sets the "outcoming" field.
func (u *GeneralUpsertBulk) SetOutcoming(v decimal.Decimal) *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.SetOutcoming(v)
	})
}

// UpdateOutcoming sets the "outcoming" field to the value that was provided on create.
func (u *GeneralUpsertBulk) UpdateOutcoming() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateOutcoming()
	})
}

// ClearOutcoming clears the value of the "outcoming" field.
func (u *GeneralUpsertBulk) ClearOutcoming() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearOutcoming()
	})
}

// SetSpendable sets the "spendable" field.
func (u *GeneralUpsertBulk) SetSpendable(v decimal.Decimal) *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.SetSpendable(v)
	})
}

// UpdateSpendable sets the "spendable" field to the value that was provided on create.
func (u *GeneralUpsertBulk) UpdateSpendable() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.UpdateSpendable()
	})
}

// ClearSpendable clears the value of the "spendable" field.
func (u *GeneralUpsertBulk) ClearSpendable() *GeneralUpsertBulk {
	return u.Update(func(s *GeneralUpsert) {
		s.ClearSpendable()
	})
}

// Exec executes the query.
func (u *GeneralUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GeneralCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GeneralCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GeneralUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
