// Code generated by ent, DO NOT EDIT.

package detail

import (
	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/service-template/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// AutoID applies equality check predicate on the "auto_id" field. It's identical to AutoIDEQ.
func AutoID(v int) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAutoID), v))
	})
}

// SampleCol applies equality check predicate on the "sample_col" field. It's identical to SampleColEQ.
func SampleCol(v string) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSampleCol), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...uint32) predicate.Detail {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...uint32) predicate.Detail {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...uint32) predicate.Detail {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...uint32) predicate.Detail {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...uint32) predicate.Detail {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...uint32) predicate.Detail {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v uint32) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDeletedAt), v))
	})
}

// AutoIDEQ applies the EQ predicate on the "auto_id" field.
func AutoIDEQ(v int) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAutoID), v))
	})
}

// AutoIDNEQ applies the NEQ predicate on the "auto_id" field.
func AutoIDNEQ(v int) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAutoID), v))
	})
}

// AutoIDIn applies the In predicate on the "auto_id" field.
func AutoIDIn(vs ...int) predicate.Detail {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldAutoID), v...))
	})
}

// AutoIDNotIn applies the NotIn predicate on the "auto_id" field.
func AutoIDNotIn(vs ...int) predicate.Detail {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldAutoID), v...))
	})
}

// AutoIDGT applies the GT predicate on the "auto_id" field.
func AutoIDGT(v int) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAutoID), v))
	})
}

// AutoIDGTE applies the GTE predicate on the "auto_id" field.
func AutoIDGTE(v int) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAutoID), v))
	})
}

// AutoIDLT applies the LT predicate on the "auto_id" field.
func AutoIDLT(v int) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAutoID), v))
	})
}

// AutoIDLTE applies the LTE predicate on the "auto_id" field.
func AutoIDLTE(v int) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAutoID), v))
	})
}

// SampleColEQ applies the EQ predicate on the "sample_col" field.
func SampleColEQ(v string) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSampleCol), v))
	})
}

// SampleColNEQ applies the NEQ predicate on the "sample_col" field.
func SampleColNEQ(v string) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSampleCol), v))
	})
}

// SampleColIn applies the In predicate on the "sample_col" field.
func SampleColIn(vs ...string) predicate.Detail {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldSampleCol), v...))
	})
}

// SampleColNotIn applies the NotIn predicate on the "sample_col" field.
func SampleColNotIn(vs ...string) predicate.Detail {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldSampleCol), v...))
	})
}

// SampleColGT applies the GT predicate on the "sample_col" field.
func SampleColGT(v string) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSampleCol), v))
	})
}

// SampleColGTE applies the GTE predicate on the "sample_col" field.
func SampleColGTE(v string) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSampleCol), v))
	})
}

// SampleColLT applies the LT predicate on the "sample_col" field.
func SampleColLT(v string) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSampleCol), v))
	})
}

// SampleColLTE applies the LTE predicate on the "sample_col" field.
func SampleColLTE(v string) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSampleCol), v))
	})
}

// SampleColContains applies the Contains predicate on the "sample_col" field.
func SampleColContains(v string) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSampleCol), v))
	})
}

// SampleColHasPrefix applies the HasPrefix predicate on the "sample_col" field.
func SampleColHasPrefix(v string) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSampleCol), v))
	})
}

// SampleColHasSuffix applies the HasSuffix predicate on the "sample_col" field.
func SampleColHasSuffix(v string) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSampleCol), v))
	})
}

// SampleColIsNil applies the IsNil predicate on the "sample_col" field.
func SampleColIsNil() predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldSampleCol)))
	})
}

// SampleColNotNil applies the NotNil predicate on the "sample_col" field.
func SampleColNotNil() predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldSampleCol)))
	})
}

// SampleColEqualFold applies the EqualFold predicate on the "sample_col" field.
func SampleColEqualFold(v string) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSampleCol), v))
	})
}

// SampleColContainsFold applies the ContainsFold predicate on the "sample_col" field.
func SampleColContainsFold(v string) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSampleCol), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Detail) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Detail) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Detail) predicate.Detail {
	return predicate.Detail(func(s *sql.Selector) {
		p(s.Not())
	})
}
